voting/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ActiveVotingView.as_view(),name="active_voting"),
    path("votes/complete", views.CompleteVotingView.as_view(),name="voting_complete"),
    path("votes/<str:slug>", views.voting_detail,name="voting_detail"),
]

votings_km/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('voting.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/models.py
from django.db import models
from django.urls import reverse

class Voting(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название")
    date_start = models.DateTimeField(verbose_name="Дата начала")
    date_finish = models.DateTimeField(verbose_name="Дата завершения")
    early_count = models.IntegerField(default=0,verbose_name="Голоса для для победы")
    completed=models.BooleanField(default=False,verbose_name="Завершено")
    persons = models.ManyToManyField('Persona', related_name='votings')
    winner = models.CharField(blank=True,max_length=255,verbose_name="Победитель")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name="Голосование"
        verbose_name_plural = "Голосования"

    def get_absolute_url(self):
        return reverse('voting_detail', kwargs={"slug": self.name})

    @property
    def get_winners(self):
        if self.completed:
            persons=self.persons.all()
            win_list=[(f'{person.first_name} {person.surname} {person.last_name}'
                       ,person.votes.filter(voting=self).count()
                       ) for person in persons]
            return sorted(win_list, key=lambda x: x[1],reverse=True)


class Votes(models.Model):
    voting = models.ForeignKey(Voting,on_delete=models.CASCADE)
    persona = models.ForeignKey("Persona",related_name="votes",
                                on_delete=models.CASCADE)
    votes_count = models.IntegerField(default=0)


class Persona(models.Model):
    first_name = models.CharField(max_length=155,verbose_name="Имя")
    surname = models.CharField(max_length=155,verbose_name="Отчество")
    last_name = models.CharField(max_length=155,verbose_name="Фамилия")
    photo = models.ImageField(verbose_name="Фотография")
    age = models.IntegerField(verbose_name="Возраст")
    bio = models.TextField(verbose_name="Биография")

    def __str__(self):
        return f"{self.first_name} {self.surname} {self.last_name}"

    class Meta:
        verbose_name="Кандидат"
        verbose_name_plural = "Кандидаты"

voting/views.py
import json

from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView
from .models import Voting,Votes,Persona
from django.utils import timezone



class ActiveVotingView(ListView):
    template_name = 'voting/index.html'
    def get_queryset(self):
        queryset=Voting.objects.filter(completed=False)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        voting = Voting.objects.filter(completed=False)
        leaders_voting = [['Лидеры', 'Голоса', ],
                          ['Нет активных голосований', 0]
                          ]
        if voting:
            all_data_raw = [[[f'{one_voting.name}/ {person.last_name}',
                                    person.votes.filter(voting=one_voting).count()]
                                    for person in one_voting.persons.all()]
                                    for one_voting in voting]
            leaders_voting=[max(data, key=lambda item: item[1])
                            for data in all_data_raw]
            leaders_voting.insert(0, ['Лидеры', 'Голоса', ])

        context["table_data"] = json.dumps(leaders_voting)
        return context

class CompleteVotingView(ListView):
    template_name = 'voting/complete.html'
    def get_queryset(self):
        queryset=Voting.objects.filter(completed=True)
        return queryset


def voting_detail(request, slug):
    if request.method == 'GET':
        voting=Voting.objects.get(name=slug)
        persons=voting.persons.all()
        context=[]
        for persona in persons:
            votes,_=persona.votes.get_or_create(voting=voting)
            context.append({
               "id":persona.id,
               "first_name":persona.first_name,
               "surname":persona.surname,
               "last_name":persona.last_name,
               "photo":persona.photo.url,
               "age":persona.age,
               "bio":persona.bio,
               "votes":votes.votes_count,
                })
        if voting.completed:

            context=sorted(context, key=lambda x: x['votes'],reverse=True)
            context[0]['victory']=True
            voting.winner=f'{context[0].get("first_name")} ' \
                          f'{context[0].get("surname")} ' \
                          f'{context[0].get("last_name")}'
            voting.save()
        timl=voting.date_finish-timezone.now()
        ds, hs, min = timl.days, timl.seconds // 3600, timl.seconds // 60 % 60
        return render(request,
                      'voting/voting.html', {
                              "context":context,
                              "voting_completed":voting.completed,
                              "time_lost":f"Дней:{ds},Часов:{hs},Минут:{min}"})

    if request.method == 'POST':
        persona_id = request.POST.get("pers_id")
        persona=Persona.objects.get(id=persona_id)
        voting = persona.votings.get(name=slug)
        votes, _ = Votes.objects.get_or_create(voting=voting, persona=persona)
        if 0 < voting.early_count <= votes.votes_count :
            voting.completed = True
            voting.save()
        else:
            votes.votes_count += 1
            votes.save()
        return redirect(reverse('voting_detail', kwargs={"slug": slug}))

templates/add_button.html
 
{% extends "admin/change_form.html" %}
{% load i18n %}


    {% block submit_buttons_bottom %}
    {% if original and original.completed %}
    <div class="submit-row">
       <input type="submit" value="{% trans 'Создать отчет' %}" name="_orderbutton" />
    </div>
    {% endif %}

    {{ block.super }}
    {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"

          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Голосование</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'active_voting' %}">Главная </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'voting_complete' %}">Завершенные голосования</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:login' %}">Админ-панель</a>
            </li>

        </ul>
    </div>
</nav>
{% block content %}
{% endblock content %}

</body>
</html>

templates/voting/complete.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid ">
<ul class="list-group">
{% for voting in voting_list %}
    <li class="list-group-item "><a href="{{voting.get_absolute_url}}">{{voting.name}}</a></li>
{%endfor%}
</ul>
    </div>
{% endblock content %}

templates/voting/index.html
{% extends 'base.html' %}
{% block content %}
   <script>
   var table_data = "{{table_data | escapejs}}";
   google.charts.load('current', {packages: ['corechart', 'bar']});
   google.charts.setOnLoadCallback(drawBasic);
function drawBasic() {
      var data = google.visualization.arrayToDataTable(JSON.parse(table_data));
      var options = {
        title: 'Промежуточные итоги',
        chartArea: {width: '50%'},
        hAxis: {
          title: 'Голоса',
          minValue: 0
        },
        vAxis: {
          title: 'Голосование/Кандидат'
        }
      };
      var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
   </script>

<div class="container-fluid ">
<ul class="list-group">
{% for vot in voting_list %}
 <li class="list-group-item "><a href="{{vot.get_absolute_url}}">{{vot.name}}</a></li>
{% endfor %}
</ul>
    </div>
<div id="chart_div"></div>

{% endblock content %}

templates/voting/voting.html
{% extends 'base.html' %}
{% block content %}

    {% if not voting_completed %}
        <h5>Осталось времени <span class="badge badge-secondary">{{ time_lost }}</span></h5>

    {% else %}
        <div class="container">Голосование завершено</div>
    {% endif %}
    <div class="row">
    {% for persona in context %}
        <form action="" method="post">{% csrf_token %}
            <div class="col-sm-6">
                <div class="card" style="width: 18rem;">
                    {% if persona.victory %}
                        <span class="text-danger text-center ">Победитель!!! Голоса:{{ persona.votes }}  </span>
                    {% else %}
                        <span class="text-info text-center ">Голоса: {{ persona.votes }}</span>
                    {% endif %}
                    <img class="card-img-top" width="200px" height="300px" src="{{ persona.photo }}" alt="Photo">
                    <div class="card-body ">
                        <h5 class="card-title "style="height: 60px">{{ persona.first_name }} {{ persona.surname }} {{ persona.last_name }}
                            ,{{ persona.age }} лет</h5>
                        <p class="card-text ">{{ persona.bio|truncatechars:100 }}.</p>
                        <input type="hidden" name="pers_id" value="{{ persona.id }}">
                        {% if not voting_completed %}
                            <button type="submit" class="btn btn-primary">Голосовать</button>
                        {% endif %}

                    </div>
                </div>
            </div>

        </form>
    {% endfor %}


{% endblock content %}

templates/voting/voting_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for vot in voting_list %}
<a href="{{vot.get_absolute_url}}">{{vot.name}}</a>

{% endfor %}
</body>
</html>